### ISSUE TITLE
Create initial Jekyll pages skeleton

### ISSUE THREAD

**Issue by filfreire** [PortoTestersMeetup/foxhound#2]
## Tasks
- [x] Create Jekyll pages skeleton ([reference](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/))
- [x] add build documentation

- [x] Overall design - issue #4 
- [x] Team - issue #10 
- [x] Temporary logo and favicon #12
- [x] About
- [x] Call for Speakers
- [x] Schedule
- [x] Speakers
- [x] Sponsors
- [x] Contacts
- [x] Venue
- [x] Change Name to "PTM Conf" #13

**Comment by filfreire** [comment]
Close
