### ISSUE TITLE
Pick and Setup overall design for website

### ISSUE THREAD

**Issue by filfreire** [PortoTestersMeetup/foxhound#4]
## Tasks
- [x] Choose a template - [zeppelin](https://github.com/gdg-x/zeppelin)
- [x] Apply changes to `Gemfile`, `_config.yml` and other possible necessary files to apply theme
- [x] Test basic functionality and visual aspect on Desktop and Mobile

Examples websites:
1. http://www.australiantestingdays.com/
2. https://agiletestingdays.com
3. http://swisstestingday.ch/en/
4. https://ukstar.eurostarsoftwaretesting.com/
5. http://lets-test.com/?page_id=4067

**Comment by filfreire** [comment]
Closing issue, work was done in PR #6
